### ISSUE TITLE
Developer Productivity Q&A

### ISSUE THREAD

**Issue by sdaschner** [sdaschner/live-qa-sessions#3]
Live on Mon, 15th June, 2020 at 6 pm CEST / 12 pm EDT / 9 am PDT, for 45 mins.

Watch [here](https://www.youtube.com/watch?v=vRgzVdXf2fA)

For more information, which material to watch upfront, see this [blog post](https://blog.sebastian-daschner.com/entries/developer-productivity-question-answer-session-june).

**Comment by sdaschner** [comment]
Via email: In your video course and resources you say that we should spend as much time on the keyboard as possible. However, in the browser I mostly use the mouse and I'm not sure if I'd be more effective with the keyboard... What are your thoughts on this?

**Comment by sdaschner** [comment]
Via email: About this current situation, can you share what has changed from your way of working and especially your productivity? Do you have some tips for those who are still struggling with all that's going on?

**Comment by nicholasjorge** [comment]
How can you be productive as soon as possible when switching from one OS to another?(Win to Mac)

**Comment by jeshan** [comment]
hi Sebastian, this week I rewatched your VirtualJUG presentation about productivity and it was great!

Today you just mentioned a similar extension but I like "Key Jump" for Chrome:
https://chrome.google.com/webstore/detail/key-jump-keyboard-navigat/afdjhbmagopjlalgcjfclkgobaafamck

What I like is that it is number-driven, instead of letter-driven.

It works great especially when there's a sea of links:
![image](https://user-images.githubusercontent.com/1020565/84681406-21080780-af45-11ea-8fe5-4a67cb9f0a78.png)


Jeshan from Mauritius

**Comment by arielsantana** [comment]
Hi Sebastian, in my experience, the most of dev's use the RUN mode when they programming and tests their apps. But I prefer use the DEBUG mode. I think that mode is better ​because give us the posibility of modify the code, and re-run the method and continue with the flow, without restart the app and build the test case again ​(set variables, modifiy database, configure another microservices, etc.). What's your opinion about that?

**Comment by sdaschner** [comment]
Thanks for attending!

Some resources I've mentioned:

https://anchor.fm/effective-developer
https://ultimatehackingkeyboard.com/
https://blog.sebastian-daschner.com/entries/chroma-keying-video-setup
https://openliberty.io/guides/
